// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCY3SURcElSavfbmvnZrSfWQQLC87if5ak',
    appId: '1:892182850935:web:9e9365f1dabbbd5dd80572',
    messagingSenderId: '892182850935',
    projectId: 'turing-cell-410207',
    authDomain: 'turing-cell-410207.firebaseapp.com',
    storageBucket: 'turing-cell-410207.appspot.com',
    measurementId: 'G-TTPZR89NKM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM13DAkGobytvEwI4zoQQQV0jJh7yIxjk',
    appId: '1:892182850935:android:45947bacb361e01ad80572',
    messagingSenderId: '892182850935',
    projectId: 'turing-cell-410207',
    storageBucket: 'turing-cell-410207.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaQ7LGc-K7xWJ9gwCy-uEkIyRdi5OGsxI',
    appId: '1:892182850935:ios:8effc96a5183d63bd80572',
    messagingSenderId: '892182850935',
    projectId: 'turing-cell-410207',
    storageBucket: 'turing-cell-410207.appspot.com',
    iosClientId: '892182850935-f70lbg9i7h8d0p06tv4mt5i44j42taa5.apps.googleusercontent.com',
    iosBundleId: 'com.example.octoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaQ7LGc-K7xWJ9gwCy-uEkIyRdi5OGsxI',
    appId: '1:892182850935:ios:7a726a77b8f47b8cd80572',
    messagingSenderId: '892182850935',
    projectId: 'turing-cell-410207',
    storageBucket: 'turing-cell-410207.appspot.com',
    iosClientId: '892182850935-dc5eq4he2cneiiqaegd9p2had543r29a.apps.googleusercontent.com',
    iosBundleId: 'com.example.octoApp.RunnerTests',
  );
}
